# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestKatalon():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_katalon(self):
        # Test name: Katalon
        # Step # | name | target | value
        # 1 | open | / |
        self.driver.get("https://katalon-demo-cura.herokuapp.com/")
        # 2 | setWindowSize | 1936x1048 |
        self.driver.set_window_size(1936, 1048)
        # 3 | click | id=btn-make-appointment |
        self.driver.find_element(By.ID, "btn-make-appointment").click()
        # 4 | click | id=txt-username |
        self.driver.find_element(By.ID, "txt-username").click()
        # 5 | type | id=txt-username | suraj
        self.driver.find_element(By.ID, "txt-username").send_keys("suraj")
        # 6 | type | id=txt-password | test123
        self.driver.find_element(By.ID, "txt-password").send_keys("test123")
        # 7 | click | id=btn-login |
        self.driver.find_element(By.ID, "btn-login").click()